[project]
name = "daylio-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "bcrypt>=4.3.0",
    "dotenv>=0.9.9",
    "pandas>=2.3.2",
    "streamlit>=1.49.1",
]
